### ISSUE TITLE
Getting the following error when trying to create a new app

### ISSUE THREAD

**Issue by cmydur** [lidia-freitas/generator-aspnet-angular#1]
? Your project name test
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, no such file or directory 'C:\temp\AngularLearning\angularasp\Web
.config'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.readFileAsString (C:\Users\User\AppData\Roaming\npm\node_modu
les\generator-aspnet-angular\node_modules\html-wiring\index.js:281:13)
    at module.exports.yeoman.Base.extend.writing (C:\Users\User\AppData\Roa
ming\npm\node_modules\generator-aspnet-angular\generators\app\index.js:30:32)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\g
enerator-aspnet-angular\node_modules\yeoman-generator\lib\base.js:431:23)
    at C:\Users\User\AppData\Roaming\npm\node_modules\generator-aspnet-angu
lar\node_modules\yeoman-generator\node_modules\run-async\index.js:26:25
    at C:\Users\User\AppData\Roaming\npm\node_modules\generator-aspnet-angu
lar\node_modules\yeoman-generator\node_modules\run-async\index.js:25:19
    at C:\Users\User\AppData\Roaming\npm\node_modules\generator-aspnet-angu
lar\node_modules\yeoman-generator\lib\base.js:432:9
    at processImmediate [as _immediateCallback](timers.js:367:17)

**Comment by bbuczek** [comment]
I get similar error:
npm -v 3.10.8
nodejs --version = v4.5.0
yo --version = 1.4.6

? Your project name AngularByLidia
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\TheUser\Source\Repos\YoGenerated\aspangByLidiaDefreitas\Web.con
fig'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.readFileAsString (C:\Users\TheUser\AppData\Roaming\npm\node_modules\generator-aspnet-angular\node_modules\
html-wiring\index.js:281:13)
    at module.exports.yeoman.Base.extend.writing (C:\Users\TheUser\AppData\Roaming\npm\node_modules\generator-aspnet-ang
ular\generators\app\index.js:30:32)
    at Object.<anonymous> (C:\Users\TheUser\AppData\Roaming\npm\node_modules\generator-aspnet-angular\node_modules\yeoma
n-generator\lib\base.js:431:23)
    at C:\Users\TheUser\AppData\Roaming\npm\node_modules\generator-aspnet-angular\node_modules\run-async\index.js:26:25
    at C:\Users\TheUser\AppData\Roaming\npm\node_modules\generator-aspnet-angular\node_modules\run-async\index.js:25:19
    at C:\Users\TheUser\AppData\Roaming\npm\node_modules\generator-aspnet-angular\node_modules\yeoman-generator\lib\base
.js:432:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by rjcarneiro** [comment]
Hi,

It's expecting that Web.config exists on the folder that you're creating the aspnet-angular project. I think this is a design issue. Hope @lidia-freitas could fix this in order to create a project from the scratch.

**Comment by cmydur** [comment]
I created an empty Web.config file and it worked, however it was expecting RouteConfig.cs in App_Start folder as well. Creating these empty files seems to have worked

**Comment by tazmanrising** [comment]
I can confirm that cmydur is correct

**Comment by lidia-freitas** [comment]
Hi everyone,
Sorry for the delay. This generator must run inside a already created asp.net project. I updated the readme file with better instructions.
